Bugfix: Set loader on local copy of jinja environment
nornir-automation/nornir_jinja2 pull request #5
Opened 2021-05-19 11:49 UTC by indy-independence

When adding the feature to specify a user defined jinja_env I think I opened up an opportunity for users to shoot themselves in the foot (I certainly did myself) by setting the env.loader in the referenced jinja_env argument instead of a local copy of the jinja_env object. If the code calling template_file uses the same jinja_env object in two threads with different FileSystemLoader paths, for example when one thread renders EOS templates from one directory and another thread renders JunOS templates from another directory, they will both update the same env.loader path causing the right templates not to be found. This could be fixed by the code calling template_file of course, but I think it's probably safer to fix with something like this patch maybe?

2021-05-20 14:11 UTC, dbarrosop commented
Would you mind adding an example of code that reproduces the issue you describe?

2021-05-21 08:03 UTC, indy-independence commented
Yes I have something like this:
```
cnaas_jinja_env = JinjaEnvironment(
    trim_blocks=True,
    lstrip_blocks=True,
    keep_trailing_newline=True
)

def blabla():
    r = task.run(task=template_file,
                 name="Generate device config",
                 template=template,
                 jinja_env=cnaas_jinja_env,
                 path=f"{local_repo_path}/{task.host.platform}",
                 **template_vars)
```

If the inventory that you run the task on contains both devices with task.host.platform eos and junos for example you will get errors with templates not found or including wrong templates etc.

2021-05-25 11:38 UTC, dbarrosop commented
Mmm, I think the main issue here is supporting both passing the env and path at the same time. I think that if we send the environment we shouldn't make any modification to it and simply pass it around. So the way I see it we should change the plugin to:

``` python
    if jinja_env:
        env = jinja_env
    else:
        env = Environment(
            loader=FileSystemLoader(path), undefined=StrictUndefined, trim_blocks=True,
        )
```

And then, in your code you'd have something like:


``` python
def per_vendor_env(path):
   return JinjaEnvironment(
       trim_blocks=True,
       lstrip_blocks=True,
       keep_trailing_newline=True,
       loader=FileSystemLoader(path),
   )

def blabla():
    r = task.run(task=template_file,
                 name="Generate device config",
                 template=template,
                 jinja_env= per_vendor_env(f"{local_repo_path}/{task.host.platform}"),
                 **template_vars)
```

Thoughts?

2021-05-25 14:13 UTC, indy-independence commented
Yes that also makes sense to me. It might break some stuff on my end  when I upgrade nornir, but as long as I patch my code before upgrading I think it should be fine :)

2026-06-13 13:13 UTC, Qwiko commented
Is there any update to this?

2026-06-13 18:58 UTC, Qwiko requested changes
I think it is better to only overwrite the loader if it is actually not defined.
That way it will not be mutated over threads and users can still use jinja2 env caching between tasks and threads. If there is a local copy caching wont work.

2026-06-13 18:58 UTC, Qwiko commented on nornir_jinja2/plugins/tasks/template_file.py
> +        env = copy.deepcopy(jinja_env)
```suggestion
        env = jinja_env
```

2026-06-13 18:58 UTC, Qwiko commented on nornir_jinja2/plugins/tasks/template_file.py
>          env.loader = FileSystemLoader(path)
```suggestion
        it not env.loader:
            env.loader = FileSystemLoader(path)
```

2026-06-13 20:45 UTC, Qwiko commented
I tested the same original issue you had @indy-independence years ago and managed to fix it with my suggested change.

I think the path variable should be changed to a optional variable and not override the loader.

I get the error even if the path variable is the same.
My guess is that it seems like in some edge-cases the loader can be garbage collected or race conditioned and jinjas lru caching breaks when running in a multi-threaded scenario where the environment and therefore cache is global and the loader is overridden/mutated across threads. But I could not fully test it and confirm my guess. I just know my suggested change solved the issue I was seeing.

2026-06-15 09:20 UTC, dbarrosop commented
@Qwiko given this PR is form 2021 I would consider it abandoned, if you have a working solution would you mind opening a PR of your own? Thanks!

2026-07-27 14:57 UTC, ogenstad commented
Closing as there are merge conflicts and the changes were merged in #17.

2026-07-27 14:57 UTC, closed without merging